server:
  port: 8501

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      database: mongo-ase-user
      uri: mongodb://localhost:27017


